#Application Configuration
server:
  port: 8091
  error:
    include-message: always
    include-binding-errors: always


# To See H2 Console in Browser:
# http://localhost:8092/h2-console
# Enabling H2 Console
spring:
  application:
    zipkin: http://localhost:9411 
  datasource:
    password: password
    url: jdbc:postgresql://postgres:5432/customerDB
    username: user
  # h2:
    # console:
      # enabled: true
  # ===============================
  # DB
  # ===============================
 ## datasource:
   # url: jdbc:h2:mem:customerDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
   # driverClassName: org.h2.Driver
   # platform: h2
   # username: sa
    #password:

  # ===============================
  # JPA / HIBERNATE
  # ===============================
   jpa:
    hibernate:
        ddl-auto: create-drop
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
    show-sql: true
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka